import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
        },
      ],
      // We use <img> intentionally for external Anitabi URLs that can't use
      // next/image (no domain control, fully-dynamic URLs from Anitabi API).
      "@next/next/no-img-element": "off",
    },
  },
  // Test files may use require() for CJS module cache busting.
  {
    files: ["tests/**/*.ts", "tests/**/*.tsx"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by MSW — not project code.
    "public/mockServiceWorker.js",
    // Generated by vitest coverage.
    "coverage/**",
  ]),
]);

export default eslintConfig;
