from typing import Self

class PostgresContainer:
    def __init__(self, image: str) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *exc: object) -> None: ...
    def get_connection_url(self) -> str: ...
