import assert from "node:assert/strict";
import test from "node:test";
import { once } from "node:events";
import { defaultWorker } from "./default-worker.ts";
import { pool } from "./postgres.ts";
import { operationToolsNetwork } from "./operation-tools-fixture.ts";
import { nativeWebServer } from "../../../apps/web/tests/native-server.ts";
import { nativeRecoveryPage, submitNativeChat, leaveAndReturn, expectNativeAnswer } from "../../../e2e/native-recovery-driver.ts";

void test("the actual browser leaves a native tool running, reconnects and recovers its structured result once", { timeout: 120_000 }, async (context) => {
  const held = Promise.withResolvers<undefined>();
  const entered = Promise.withResolvers<undefined>();
  context.after(() => { held.resolve(undefined); });
  const network = operationToolsNetwork(false);
  const native = await defaultWorker(context, {}, { ...network, catalog: async () => { entered.resolve(undefined); await held.promise; return network.catalog(); } });
  const observer = await pool.connect();
  context.after(async () => { try { await observer.query("UNLISTEN *"); } finally { observer.release(); } });
  await observer.query("UNLISTEN *; LISTEN host_test_settled");
  const settled = once(observer, "notification", { signal: context.signal }).then(() => true, () => false);
  const url = await nativeWebServer(context, await native.worker.ready);
  const page = await nativeRecoveryPage(context, url);
  const posts: string[] = [];
  page.on("request", (request) => { if (request.method() === "POST" && request.url().endsWith("/v1/chat")) posts.push(request.url()); });
  const accepted = await submitNativeChat(page);
  await entered.promise;
  await leaveAndReturn(page);
  held.resolve(undefined);
  await expectNativeAnswer(page);
  assert.equal(await settled, true);
  assert.equal(posts.length, 1);
  assert.equal(native.requests.length, 2);
  assert.equal(native.catalogRequests.length, 1);
  const result = await pool.query<{ operation_id: string; settled_at: Date | null }>("SELECT operation_id, settled_at FROM agent_settlements WHERE operation_id=$1", [accepted.operationId]);
  assert.equal(result.rows.length, 1);
  assert.ok(result.rows[0]);
  assert.equal(result.rows[0].operation_id, accepted.operationId);
  assert.ok(result.rows[0].settled_at);
  const quota = await pool.query<{ message_count: string }>("SELECT message_count FROM anon_daily_message_count");
  assert.equal(quota.rows[0]?.message_count, "1");
});
