-- Table turn_reservations (TURN-2 #949: one durable turn reservation)

CREATE TABLE public.turn_reservations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    session_id text,
    turn_key text NOT NULL,
    payer text NOT NULL,
    identity_id text,
    revision integer NOT NULL,
    digest text,
    status text DEFAULT 'in_flight'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT turn_reservations_payer_check
        CHECK ((payer = ANY (ARRAY['anon'::text, 'user'::text, 'byok'::text]))),
    CONSTRAINT turn_reservations_status_check
        CHECK ((status = ANY (ARRAY['in_flight'::text, 'completed'::text])))
);

ALTER TABLE ONLY public.turn_reservations
    ADD CONSTRAINT turn_reservations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.turn_reservations
    ADD CONSTRAINT turn_reservations_session_turn_key UNIQUE (session_id, turn_key);

ALTER TABLE ONLY public.turn_reservations
    ADD CONSTRAINT turn_reservations_session_revision UNIQUE (session_id, revision);

-- Nullable session_id rows (session-less selection turns) still need the
-- single-winner gate: Postgres UNIQUE treats NULLs as distinct, so a partial
-- index on (turn_key) alone restores it for those rows.
CREATE UNIQUE INDEX turn_reservations_null_session_key
    ON public.turn_reservations USING btree (turn_key)
    WHERE (session_id IS NULL);

CREATE INDEX idx_turn_reservations_session_revision
    ON public.turn_reservations USING btree (session_id, revision DESC);

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.turn_reservations TO agent_svc;
GRANT SELECT ON TABLE public.turn_reservations TO readonly;
