/**
 * THE zod↔JSON-Schema seam for the agent's catalog tools (spec
 * `docs/specs/2026-09-01-agent-ts-rewrite-spec.md` §二, "schema 边界").
 *
 * Decision: the contract's zod is the SOURCE — `search_bangumi`'s `^\d+$`,
 * `resolve_anime`'s non-empty title, `search_nearby`'s positive radius and
 * `plan_route`'s pacing enum are the catalog's own request constraints, already
 * declared once in `src/contract.ts` / `src/models.ts`. This script is the only
 * conversion in the repo: it runs `z.toJSONSchema` over `src/agent-tool-parameters.ts`
 * and writes `src/agent-tool-schemas.ts`, the JSON Schema `workers/edge` hands to
 * pi as a tool's `parameters`. The edge never re-declares a constraint and never
 * loads zod; `test/agent-tool-schemas.test.ts` fails on committed drift, exactly
 * as the OpenAPI documents next door do.
 *
 * Run: pnpm run emit:tool-schemas
 */

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { CATALOG_TOOL_PARAMETERS } from "../src/agent-tool-parameters.js";

const OUTPUT_PATH = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "agent-tool-schemas.ts");

const BANNER = `/**
 * GENERATED by \`pnpm run emit:tool-schemas\` — do not edit by hand.
 *
 * The JSON Schema for every catalog tool's parameters, converted once from the
 * zod in \`agent-tool-parameters.ts\`. See \`scripts/emit-tool-schemas.ts\` for why
 * this is the repo's only zod↔JSON-Schema conversion (spec §二).
 *
 * This module imports no value, so \`workers/edge\` can load it under node:test.
 */

import type { CatalogToolName } from "./agent-tool-parameters.js";

/** One parameter's constraints, as the model's provider receives them. */
export interface ToolParameterProperty {
  type: string;
  description?: string;
  minLength?: number;
  pattern?: string;
  enum?: string[];
  exclusiveMinimum?: number;
  maximum?: number;
}

/** One tool's parameter object: what pi validates a tool call against. */
export interface ToolParameterSchema {
  $schema: string;
  type: "object";
  properties: Record<string, ToolParameterProperty>;
  required?: string[];
  additionalProperties: false;
}
`;

/** Convert one tool's zod parameters to the JSON Schema the provider sees. */
function jsonSchemaFor(parameters: z.ZodType): unknown {
  return z.toJSONSchema(parameters, { io: "input", target: "draft-2020-12" });
}

/** The generated module's body: one entry per tool, keyed by tool name. */
function schemaTable(): string {
  const entries = Object.entries(CATALOG_TOOL_PARAMETERS).map(
    ([name, parameters]) => `  ${name}: ${JSON.stringify(jsonSchemaFor(parameters), null, 2).replaceAll("\n", "\n  ")},`,
  );
  return `\n/** Every catalog tool's parameter schema, keyed by the name the model calls. */\nexport const CATALOG_TOOL_SCHEMAS: Record<CatalogToolName, ToolParameterSchema> = {\n${entries.join("\n")}\n};\n`;
}

/** The full text of `src/agent-tool-schemas.ts`. */
export function toolSchemaModule(): string {
  return `${BANNER}${schemaTable()}`;
}

/** The path the emitted module is committed at. */
export const TOOL_SCHEMA_MODULE_PATH = OUTPUT_PATH;

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(OUTPUT_PATH, toolSchemaModule(), "utf8");
  process.stdout.write(`wrote ${OUTPUT_PATH}\n`);
}
