/**
 * Emit the Agent boundary Python models from packages/contract/src/agent-contract.ts.
 *
 * Deterministic: schema key order drives output order; a second run produces
 * byte-identical output (enforced by the drift gate and agent-boundary.test.ts).
 * Supported: string / boolean / number / integer / nested object / array of
 * supported types / single-const or enum literals / nullability (a union with
 * exactly one non-null branch). Anything else — true unions, date-time
 * formats, arrays of unions — THROWS: an unsupported schema construct must
 * fail, never silently degrade.
 *
 * Output: apps/agent/src/animichi/interfaces/boundary/agent_models.py (committed).
 *
 * Run: pnpm emit:agent-python  (from packages/contract/)
 */

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import {
  AGENT_PATHS,
  ByokProbeResponse,
  EndpointMap,
  GetSessionHistoryResponse,
  GpsPoint,
  PhotoCandidate,
  PhotoConfirmRequest,
  PhotoPoint,
  PhotoResults,
  PhotoSearchRequest,
  PhotoSearchResponse,
  RootMetadata,
  ServiceMetadata,
  SessionHistoryMessage,
} from "../src/agent-contract.js";

const MODELS: Array<{ name: string; schema: z.ZodType }> = [
  { name: "EndpointMap", schema: EndpointMap },
  { name: "ServiceMetadata", schema: ServiceMetadata },
  { name: "RootMetadata", schema: RootMetadata },
  { name: "ByokProbeResponse", schema: ByokProbeResponse },
  { name: "GpsPoint", schema: GpsPoint },
  { name: "PhotoSearchRequest", schema: PhotoSearchRequest },
  { name: "PhotoCandidate", schema: PhotoCandidate },
  { name: "PhotoPoint", schema: PhotoPoint },
  { name: "PhotoResults", schema: PhotoResults },
  { name: "PhotoSearchResponse", schema: PhotoSearchResponse },
  { name: "PhotoConfirmRequest", schema: PhotoConfirmRequest },
  { name: "SessionHistoryMessage", schema: SessionHistoryMessage },
  { name: "GetSessionHistoryResponse", schema: GetSessionHistoryResponse },
];

const HEADER = `# GENERATED by packages/contract/scripts/emit-agent-python.ts — DO NOT EDIT.
# Source: packages/contract/src/agent-contract.ts (CONTRACT-1 #938).
# Regenerate: pnpm emit:agent-python
`;

type JsonSchema = {
  type?: string;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  enum?: string[];
  const?: string | boolean | number;
  format?: string;
  anyOf?: JsonSchema[];
  items?: JsonSchema;
};

/** True when `prop` is a single-`null` union (`z.string().nullable()`):
 * exactly two members, one of which is `null`. Wider unions stay
 * unsupported — nullable is the only union the probe contract needs. */
function isNullableUnion(prop: JsonSchema): boolean {
  const { anyOf } = prop;
  if (!anyOf || anyOf.length !== 2) return false;
  return anyOf.filter((member) => member.type === "null").length === 1;
}

function nullableInner(prop: JsonSchema): JsonSchema {
  return prop.anyOf!.find((member) => member.type !== "null")!;
}

function toJsonSchema(schema: z.ZodType): JsonSchema {
  return z.toJSONSchema(schema) as unknown as JsonSchema;
}

function nullableBranch(prop: JsonSchema): JsonSchema | undefined {
  const branches = prop.anyOf;
  if (!branches) return undefined;
  const nonNull = branches.filter((branch) => branch.type !== "null");
  if (nonNull.length !== 1) {
    throw new Error(`unsupported schema construct: union must be a single type + null`);
  }
  return nonNull[0];
}

function unwrapNullable(prop: JsonSchema, at: string): { inner: JsonSchema; nullable: boolean } {
  const inner = nullableBranch(prop);
  if (!inner) return { inner: prop, nullable: false };
  const nested = nullableBranch(inner);
  if (nested) return { inner: nested, nullable: true };
  return { inner, nullable: true };
}

function itemSchema(prop: JsonSchema, at: string): JsonSchema {
  if (prop.type !== "array" || !prop.items) {
    throw new Error(`unsupported schema construct at ${at}: type=${prop.type ?? "unknown"} (array requires items)`);
  }
  return prop.items;
}

function assertSupported(prop: JsonSchema, at: string): void {
  if (isNullableUnion(prop)) {
    assertSupported(nullableInner(prop), at);
    return;
  }
  if (prop.format) {
    throw new Error(`unsupported schema construct at ${at}: format=${prop.format} (only plain strings are supported)`);
  }
  const { inner } = unwrapNullable(prop, at);
  if (inner.type === "array") {
    assertSupported(itemSchema(inner, at), at);
    return;
  }
  if (inner.type !== "string" && inner.type !== "boolean" && inner.type !== "number" && inner.type !== "integer" && inner.type !== "object") {
    throw new Error(`unsupported schema construct at ${at}: type=${inner.type ?? "unknown"} (only string/boolean/number/integer/object/array are supported)`);
  }
}

function pyLiteral(value: string | boolean | number): string {
  if (value === true) return "True";
  if (value === false) return "False";
  return JSON.stringify(value);
}

function fieldType(prop: JsonSchema, at: string): string {
  assertSupported(prop, at);
  const { inner } = unwrapNullable(prop, at);
  if (inner.const !== undefined) return `Literal[${pyLiteral(inner.const)}]`;
  if (inner.enum && inner.enum.length > 0) {
    return `Literal[${inner.enum.map((value) => pyLiteral(value)).join(", ")}]`;
  }
  if (inner.type === "boolean") return "bool";
  if (inner.type === "number") return "float";
  if (inner.type === "integer") return "int";
  if (inner.type === "object") return nestedClassName(at);
  if (inner.type === "array") {
    const item = unwrapNullable(itemSchema(inner, at), at);
    const itemType = fieldType(item.inner, at);
    return item.nullable ? `list[${itemType} | None]` : `list[${itemType}]`;
  }
  return "str";
}

function nestedClassName(fieldPath: string): string {
  return fieldPath
    .split(".")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function renderNestedChildren(name: string, properties: Record<string, JsonSchema>, fieldPath: string, out: string[]): void {
  for (const [child, childProp] of Object.entries(properties)) {
    const childAt = `${fieldPath}.${child}`;
    const inner = unwrapNullable(childProp, childAt).inner;
    if (inner.type === "array") {
      const items = itemSchema(inner, childAt);
      // Only array items that are objects get a nested class; primitive item
      // types are handled purely through `fieldType` (e.g. `list[str]`).
      if (items.type === "object" && items.properties) {
        const childName = nestedClassName(childAt);
        renderNestedChildren(childName, items.properties, childAt, out);
        renderNestedClass(childName, items, childAt, out);
      }
      continue;
    }
    if (inner.type !== "object" || !inner.properties) continue;
    const childName = nestedClassName(childAt);
    renderNestedChildren(childName, inner.properties, childAt, out);
    renderNestedClass(childName, inner, childAt, out);
  }
}

function renderNestedClass(name: string, prop: JsonSchema, fieldPath: string, out: string[]): void {
  const required = new Set(prop.required ?? []);
  out.push(`class ${name}(BaseModel):`);
  for (const [child, childProp] of Object.entries(prop.properties ?? {})) {
    const at = `${fieldPath}.${child}`;
    const { nullable } = unwrapNullable(childProp, at);
    const base = fieldType(childProp, at);
    const optional = !required.has(child);
    if (optional) {
      out.push(`    ${child}: ${base} | None = None`);
    } else if (nullable) {
      out.push(`    ${child}: ${base} | None`);
    } else {
      out.push(`    ${child}: ${base}`);
    }
  }
  out.push("", "");
}

function renderModel(name: string, schema: z.ZodType): string[] {
  const out: string[] = [];
  const json = toJsonSchema(schema);
  renderNestedChildren(name, json.properties ?? {}, name, out);
  renderNestedClass(name, json, name, out);
  return out;
}

function collectTypingImports(json: JsonSchema, typing: string[], path: string): void {
  for (const [field, prop] of Object.entries(json.properties ?? {})) {
    const at = `${path}.${field}`;
    const { inner } = unwrapNullable(prop, at);
    if (inner.const !== undefined || (inner.enum && inner.enum.length > 0)) {
      if (!typing.includes("Literal")) typing.push("Literal");
    }
    if (inner.type === "object") {
      collectTypingImports(inner, typing, at);
    } else if (inner.type === "array") {
      const items = unwrapNullable(itemSchema(inner, at), at).inner;
      if (items.type === "object") {
        collectTypingImports(items, typing, at);
      }
    }
  }
}

function renderImports(): string[] {
  const typing: string[] = [];
  for (const model of MODELS) {
    collectTypingImports(toJsonSchema(model.schema), typing, model.name);
  }
  const lines: string[] = [];
  if (typing.length > 0) lines.push(`from typing import ${typing.join(", ")}`);
  lines.push("", "from pydantic import BaseModel");
  return lines;
}

function pyString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

function renderInventory(): string[] {
  const entries = AGENT_PATHS.map(
    (p) => `    ("${pyString(p.method)}", "${pyString(p.path)}", "${pyString(p.summary)}"),`,
  ).join("\n");
  return [
    "AGENT_PATH_INVENTORY: tuple[tuple[str, str, str], ...] = (",
    entries,
    ")",
  ];
}

export function renderContent(): string {
  const lines: string[] = [...renderImports(), "", ""];
  for (const model of MODELS) {
    lines.push(...renderModel(model.name, model.schema));
  }
  lines.push(...renderInventory());
  return `${HEADER}\n${lines.join("\n")}\n`;
}

export { collectTypingImports, renderImports, renderModel, renderInventory, toJsonSchema };

// Write the generated file only when run as a CLI (never on import — the
// test suite imports this module and must not rewrite the committed file).
const isMain = process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href;
if (isMain) {
  const outPath = join(
    dirname(fileURLToPath(import.meta.url)),
    "..",
    "..",
    "..",
    "apps",
    "agent",
    "src",
    "animichi",
    "interfaces",
    "boundary",
    "agent_models.py",
  );
  writeFileSync(outPath, renderContent(), "utf8");
  process.stdout.write(`Wrote ${outPath}\n`);
}
