/**
 * Emit the Agent boundary Python models from packages/contract/src/agent-contract.ts.
 *
 * Deterministic: schema key order drives output order; a second run produces
 * byte-identical output (enforced by the drift gate and agent-boundary.test.ts).
 * Only string / boolean / nested-object fields are supported; anything else
 * (number, date-time format, union, array) THROWS — an unsupported schema
 * construct must fail, never silently degrade.
 *
 * Output: apps/agent/src/animichi/interfaces/boundary/agent_models.py (committed).
 *
 * Run: pnpm emit:agent-python  (from packages/contract/)
 */

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { AGENT_PATHS, EndpointMap, RootMetadata, ServiceMetadata } from "../src/agent-contract.js";

const MODELS: Array<{ name: string; schema: z.ZodType }> = [
  { name: "EndpointMap", schema: EndpointMap },
  { name: "ServiceMetadata", schema: ServiceMetadata },
  { name: "RootMetadata", schema: RootMetadata },
];

const HEADER = `# GENERATED by packages/contract/scripts/emit-agent-python.ts — DO NOT EDIT.
# Source: packages/contract/src/agent-contract.ts (CONTRACT-1 #938).
# Regenerate: pnpm emit:agent-python
`;

type JsonSchema = {
  type?: string;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  enum?: string[];
  const?: string | boolean | number;
  format?: string;
};

function toJsonSchema(schema: z.ZodType): JsonSchema {
  return z.toJSONSchema(schema) as unknown as JsonSchema;
}

function assertSupported(prop: JsonSchema, at: string): void {
  if (prop.format) {
    throw new Error(`unsupported schema construct at ${at}: format=${prop.format} (only plain strings are supported)`);
  }
  if (prop.type !== "string" && prop.type !== "boolean" && prop.type !== "object") {
    throw new Error(`unsupported schema construct at ${at}: type=${prop.type ?? "unknown"} (only string/boolean/object are supported)`);
  }
}

function fieldType(prop: JsonSchema, at: string): string {
  assertSupported(prop, at);
  if (prop.type === "boolean") return "bool";
  if (prop.type === "object") return nestedClassName(at);
  if (prop.const !== undefined && typeof prop.const === "string") {
    return `Literal[${JSON.stringify(prop.const)}]`;
  }
  if (prop.enum && prop.enum.length === 1) return `Literal[${JSON.stringify(prop.enum[0])}]`;
  return "str";
}

function nestedClassName(fieldPath: string): string {
  return fieldPath
    .split(".")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function renderNestedChildren(name: string, properties: Record<string, JsonSchema>, fieldPath: string, out: string[]): void {
  for (const [child, childProp] of Object.entries(properties)) {
    if (childProp.type !== "object" || !childProp.properties) continue;
    renderNestedChildren(nestedClassName(`${fieldPath}.${child}`), childProp.properties, `${fieldPath}.${child}`, out);
    renderNestedClass(nestedClassName(`${fieldPath}.${child}`), childProp, `${fieldPath}.${child}`, out);
  }
}

function renderNestedClass(name: string, prop: JsonSchema, fieldPath: string, out: string[]): void {
  const required = new Set(prop.required ?? []);
  out.push(`class ${name}(BaseModel):`);
  for (const [child, childProp] of Object.entries(prop.properties ?? {})) {
    const optional = !required.has(child);
    const type = fieldType(childProp, `${fieldPath}.${child}`);
    out.push(optional ? `    ${child}: Optional[${type}] | None = None` : `    ${child}: ${type}`);
  }
  out.push("", "");
}

function renderModel(name: string, schema: z.ZodType): string[] {
  const out: string[] = [];
  const json = toJsonSchema(schema);
  renderNestedChildren(name, json.properties ?? {}, name, out);
  renderNestedClass(name, json, name, out);
  return out;
}

function collectTypingImports(json: JsonSchema, typing: string[], path: string): void {
  for (const [field, prop] of Object.entries(json.properties ?? {})) {
    const at = `${path}.${field}`;
    if (prop.const !== undefined || (prop.enum && prop.enum.length > 0)) {
      if (!typing.includes("Literal")) typing.push("Literal");
    }
    if (!(json.required ?? []).includes(field)) {
      if (!typing.includes("Optional")) typing.push("Optional");
    }
    if (prop.type === "object") {
      collectTypingImports(prop, typing, at);
    }
  }
}

function renderImports(): string[] {
  const typing: string[] = [];
  for (const model of MODELS) {
    collectTypingImports(toJsonSchema(model.schema), typing, model.name);
  }
  const lines: string[] = [];
  if (typing.length > 0) lines.push(`from typing import ${typing.join(", ")}`);
  lines.push("", "from pydantic import BaseModel");
  return lines;
}

function pyString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

function renderInventory(): string[] {
  const entries = AGENT_PATHS.map(
    (p) => `    ("${pyString(p.method)}", "${pyString(p.path)}", "${pyString(p.summary)}"),`,
  ).join("\n");
  return [
    "AGENT_PATH_INVENTORY: tuple[tuple[str, str, str], ...] = (",
    entries,
    ")",
  ];
}

export function renderContent(): string {
  const lines: string[] = [...renderImports(), "", ""];
  for (const model of MODELS) {
    lines.push(...renderModel(model.name, model.schema));
  }
  lines.push(...renderInventory());
  return `${HEADER}\n${lines.join("\n")}\n`;
}

export { collectTypingImports, renderImports, renderModel, renderInventory, toJsonSchema };

// Write the generated file only when run as a CLI (never on import — the
// test suite imports this module and must not rewrite the committed file).
const isMain = process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href;
if (isMain) {
  const outPath = join(
    dirname(fileURLToPath(import.meta.url)),
    "..",
    "..",
    "..",
    "apps",
    "agent",
    "src",
    "animichi",
    "interfaces",
    "boundary",
    "agent_models.py",
  );
  writeFileSync(outPath, renderContent(), "utf8");
  process.stdout.write(`Wrote ${outPath}\n`);
}
