# GENERATED by packages/contract/scripts/emit-agent-python.ts — DO NOT EDIT.
# Source: packages/contract/src/agent-contract.ts (CONTRACT-1 #938).
# Regenerate: pnpm emit:agent-python

from typing import Literal

from pydantic import BaseModel


class EndpointMap(BaseModel):
    healthz: str
    runtime: str
    feedback: str


class ServiceMetadata(BaseModel):
    status: Literal["ok"]
    service: str
    git_commit: str
    git_branch: str
    started_at: str
    app_env: str
    observability_enabled: bool
    db_adapter: str
    session_store: str


class RootMetadataEndpoints(BaseModel):
    healthz: str
    runtime: str
    feedback: str


class RootMetadata(BaseModel):
    service: str
    status: Literal["ok"]
    app_env: str
    endpoints: RootMetadataEndpoints


AGENT_PATH_INVENTORY: tuple[tuple[str, str, str], ...] = (
    ("GET", "/", "service banner"),
    ("GET", "/healthz", "health and service metadata"),
    ("POST", "/v1/runtime", "runtime request"),
    ("POST", "/v1/runtime/stream", "streaming runtime request"),
    ("POST", "/v1/chat", "chat turn"),
    ("POST", "/v1/byok/probe", "probe a bring-your-own-key credential"),
    ("POST", "/v1/feedback", "submit feedback"),
    ("GET", "/v1/conversations", "list conversations"),
    ("PATCH", "/v1/conversations/{session_id}", "rename conversation"),
    ("GET", "/v1/conversations/{session_id}/messages", "conversation messages"),
    ("GET", "/v1/bangumi/{bangumi_id}/guide", "work guide points"),
    ("GET", "/v1/bangumi/nearby", "nearby points"),
    ("GET", "/v1/search/preview", "search preview"),
    ("POST", "/v1/photo-search", "photo search"),
    ("POST", "/v1/photo-search/confirm", "confirm photo offer"),
    ("POST", "/v1/session/migrate", "migrate anonymous session"),
)
