# GENERATED by packages/contract/scripts/emit-agent-python.ts — DO NOT EDIT.
# Source: packages/contract/src/agent-contract.ts (CONTRACT-1 #938).
# Regenerate: pnpm emit:agent-python

from typing import Literal

from pydantic import BaseModel


class EndpointMap(BaseModel):
    healthz: str
    runtime: str
    feedback: str


class ServiceMetadata(BaseModel):
    status: Literal["ok"]
    service: str
    git_commit: str
    git_branch: str
    started_at: str
    app_env: str
    observability_enabled: bool
    db_adapter: str
    session_store: str


class RootMetadataEndpoints(BaseModel):
    healthz: str
    runtime: str
    feedback: str


class RootMetadata(BaseModel):
    service: str
    status: Literal["ok"]
    app_env: str
    endpoints: RootMetadataEndpoints


class ByokProbeResponse(BaseModel):
    vision: bool
    reachable: bool
    error_code: str | None


class ChatTurnRequest(BaseModel):
    text: str
    session_id: str | None = None
    model: str | None = None
    locale: Literal["ja", "zh", "en"] | None = None
    include_debug: bool | None = None
    origin: str | None = None
    origin_lat: float | None = None
    origin_lng: float | None = None


class GpsPoint(BaseModel):
    lat: float
    lng: float


class PhotoSearchRequestGps(BaseModel):
    lat: float
    lng: float


class PhotoSearchRequest(BaseModel):
    image_base64: str
    mime_type: str
    gps: PhotoSearchRequestGps | None = None


class PhotoCandidate(BaseModel):
    id: str
    title: str
    bangumi_id: str | None = None


class PhotoPoint(BaseModel):
    id: str
    name: str
    bangumi_id: str
    episode: int
    screenshot_url: str
    latitude: float
    longitude: float
    title: str
    city: str | None = None


class PhotoResultsRows(BaseModel):
    id: str
    name: str
    bangumi_id: str
    episode: int
    screenshot_url: str
    latitude: float
    longitude: float
    title: str
    city: str | None = None


class PhotoResults(BaseModel):
    kind: Literal["bangumi"]
    bangumi_id: str
    title: str
    row_count: int
    rows: list[PhotoResultsRows]


class PhotoSearchResponseDataResultsRows(BaseModel):
    id: str
    name: str
    bangumi_id: str
    episode: int
    screenshot_url: str
    latitude: float
    longitude: float
    title: str
    city: str | None = None


class PhotoSearchResponseDataResults(BaseModel):
    kind: Literal["bangumi"]
    bangumi_id: str
    title: str
    row_count: int
    rows: list[PhotoSearchResponseDataResultsRows]


class PhotoSearchResponseDataCandidates(BaseModel):
    id: str
    title: str
    bangumi_id: str | None = None


class PhotoSearchResponseData(BaseModel):
    results: PhotoSearchResponseDataResults | None = None
    reason: Literal["photo_unrecognized", "photo_ambiguous"] | None = None
    candidates: list[PhotoSearchResponseDataCandidates] | None = None


class PhotoSearchResponse(BaseModel):
    success: Literal[True]
    status: Literal["ok"]
    intent: Literal["search_bangumi", "clarify"]
    offer_id: str
    data: PhotoSearchResponseData


class PhotoConfirmRequest(BaseModel):
    offer_id: str
    candidate_id: str | None = None


AGENT_PATH_INVENTORY: tuple[tuple[str, str, str], ...] = (
    ("GET", "/", "service banner"),
    ("GET", "/healthz", "health and service metadata"),
    ("POST", "/v1/chat", "chat turn"),
    ("POST", "/v1/byok/probe", "probe a bring-your-own-key credential"),
    ("POST", "/v1/feedback", "submit feedback"),
    ("GET", "/v1/conversations", "list conversations"),
    ("PATCH", "/v1/conversations/{session_id}", "rename conversation"),
    ("GET", "/v1/conversations/{session_id}/messages", "conversation messages"),
    ("GET", "/v1/bangumi/{bangumi_id}/guide", "work guide points"),
    ("GET", "/v1/bangumi/nearby", "nearby points"),
    ("GET", "/v1/search/preview", "search preview"),
    ("POST", "/v1/photo-search", "photo search"),
    ("POST", "/v1/photo-search/confirm", "confirm photo offer"),
    ("POST", "/v1/session/migrate", "migrate anonymous session"),
)
