# GENERATED by packages/contract/scripts/emit-agent-python.ts — DO NOT EDIT.
# Source: packages/contract/src/agent-contract.ts (CONTRACT-1 #938).
# Regenerate: pnpm emit:agent-python

from typing import Literal

from pydantic import BaseModel


class ServiceMetadata(BaseModel):
    status: Literal["ok"]
    service: str
    git_commit: str
    git_branch: str
    started_at: str
    app_env: str
    observability_enabled: bool
    db_adapter: str
    session_store: str


class ByokProbeResponse(BaseModel):
    vision: bool
    reachable: bool
    error_code: str | None


class ChatTurnRequest(BaseModel):
    text: str
    session_id: str | None = None
    model: str | None = None
    locale: Literal["ja", "zh", "en"] | None = None
    include_debug: bool | None = None
    origin: str | None = None
    origin_lat: float | None = None
    origin_lng: float | None = None
    selected_point_ids: list[str] | None = None
    selected_candidate_ids: list[str] | None = None
    clarification_id: int | None = None


class SessionHistoryMessageResponse_data(BaseModel):
    intent: str | None = None
    success: bool | None = None


class SessionHistoryMessage(BaseModel):
    role: str
    operation_id: str | None = None
    content: str
    response_data: SessionHistoryMessageResponse_data | None = None
    created_at: str


class GetSessionHistoryResponseMessagesResponse_data(BaseModel):
    intent: str | None = None
    success: bool | None = None


class GetSessionHistoryResponseMessages(BaseModel):
    role: str
    operation_id: str | None = None
    content: str
    response_data: GetSessionHistoryResponseMessagesResponse_data | None = None
    created_at: str


class GetSessionHistoryResponseRun(BaseModel):
    run_id: str
    status: Literal["running", "succeeded", "failed"]
    reason: (
        Literal[
            "lease_expired",
            "deadline_exceeded",
            "provider_failed",
            "tool_failed",
            "cancelled",
            "internal_error",
        ]
        | None
    ) = None


class GetSessionHistoryResponseSteps(BaseModel):
    run_id: str
    step_index: int
    tool_name: str
    params: str


class GetSessionHistoryResponse(BaseModel):
    messages: list[GetSessionHistoryResponseMessages]
    revision: int
    next_offset: int | None
    run: GetSessionHistoryResponseRun | None = None
    steps: list[GetSessionHistoryResponseSteps] | None = None


AGENT_PATH_INVENTORY: tuple[tuple[str, str, str], ...] = (
    ("GET", "/healthz", "gateway readiness"),
    ("POST", "/v1/chat", "chat turn"),
    ("POST", "/v1/byok/probe", "probe a bring-your-own-key credential"),
    ("GET", "/v1/conversations/{session_id}/messages", "conversation messages"),
)
