from typing import Self

class DockerContainer:
    def __init__(self, image: str) -> None: ...
    def with_exposed_ports(self, *ports: str | int) -> Self: ...
    def with_env(self, key: str, value: str) -> Self: ...
    def start(self) -> Self: ...
    def stop(self) -> None: ...
