/**
 * Agent boundary contract tests (CONTRACT-1 #938).
 *
 * Red/green contract for the deterministic Python emitter:
 *  - two generations are byte-identical (determinism);
 *  - emitted output equals the committed generated file (clean-tree);
 *  - deleting a health field or retained path fails;
 *  - a deliberately unsupported schema construct fails loudly.
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { z } from "zod";
import { AGENT_PATHS } from "../src/agent-paths.js";
import {
  ByokProbeErrorBody,
  ByokProbeResponse,
  ChatTurnRequest,
  GetSessionHistoryResponse,
  GpsPoint,
  PhotoConfirmRequest,
  PhotoSearchRequest,
  PhotoSearchResponse,
  ServiceMetadata,
  SessionHistoryMessage,
} from "../src/agent-contract.js";
import { renderContent, renderModel } from "../scripts/emit-agent-python.js";

const COMMITTED = readFileSync(
  join(__dirname, "..", "..", "..", "apps", "agent", "src", "animichi", "interfaces", "boundary", "agent_models.py"),
  "utf8",
);

describe("agent boundary emitter", () => {
  it("two generations are byte-identical", () => {
    const first = renderModel("ServiceMetadata", ServiceMetadata).join("\n");
    const second = renderModel("ServiceMetadata", ServiceMetadata).join("\n");
    expect(second).toBe(first);
  });

  it("emitted output matches the committed generated file (clean-tree)", () => {
    expect(renderContent()).toBe(COMMITTED);
  });

  it("generated ServiceMetadata retains every health field (deleting one fails)", () => {
    const rendered = renderModel("ServiceMetadata", ServiceMetadata).join("\n");
    for (const field of [
      "status",
      "service",
      "git_commit",
      "git_branch",
      "started_at",
      "app_env",
      "observability_enabled",
      "db_adapter",
      "session_store",
    ]) {
      expect(rendered).toContain(`    ${field}:`);
    }
  });

  it("omitting a health field from the schema drops it from the rendered model", () => {
    const withoutCommit = z.object({
      status: z.literal("ok"),
      service: z.string(),
      git_branch: z.string(),
    });
    const rendered = renderModel("ServiceMetadata", withoutCommit).join("\n");
    expect(rendered).not.toContain("git_commit");
    expect(rendered).toContain("git_branch");
  });

  it("an unsupported schema construct fails loudly", () => {
    // A date-time format string is still unsupported (only plain strings).
    expect(() => renderModel("BadModel", z.object({ at: z.string().datetime() }))).toThrow(/unsupported schema construct/);
    // z.date() cannot even reach the emitter — zod's own JSON-schema
    // conversion rejects it; either failure mode is a loud failure.
    expect(() => renderModel("BadModel", z.object({ at: z.date() }))).toThrow();
    // A true union (two non-null branches) is not expressible in the
    // generated models — it must fail rather than silently drop a branch.
    expect(() =>
      renderModel("BadModel", z.object({ value: z.union([z.string(), z.number()]) })),
    ).toThrow(/union/);
  });

  it("renders photo request DTOs with numbers, nullables, and literals (AGENT-1 #952)", () => {
    const request = renderModel("PhotoSearchRequest", PhotoSearchRequest).join("\n");
    expect(request).toContain("    image_base64: str");
    expect(request).toContain("    gps: PhotoSearchRequestGps | None = None");
    const gps = renderModel("GpsPoint", GpsPoint).join("\n");
    expect(gps).toContain("    lat: float");
    expect(gps).toContain("    lng: float");
  });

  it("renders photo response DTOs with arrays of objects (AGENT-1 #952)", () => {
    const response = renderModel("PhotoSearchResponse", PhotoSearchResponse).join("\n");
    expect(response).toContain("    success: Literal[True]");
    expect(response).toContain('    intent: Literal["search_bangumi", "clarify"]');
    expect(response).toContain("    offer_id: str");
    expect(response).toContain("    rows: list[PhotoSearchResponseDataResultsRows]");
    expect(response).toContain("    row_count: int");
    expect(response).toContain('    reason: Literal["photo_unrecognized", "photo_ambiguous"] | None = None');
    expect(response).toContain("    candidates: list[PhotoSearchResponseDataCandidates] | None = None");
  });

  it("renders the confirm DTO with an opaque offer id (AGENT-1 #952)", () => {
    const confirm = renderModel("PhotoConfirmRequest", PhotoConfirmRequest).join("\n");
    expect(confirm).toContain("    offer_id: str");
    expect(confirm).toContain("    candidate_id: str | None = None");
  });

  it("a nullable item schema emits list[str | None] (AGENT-1 #952)", () => {
    const rendered = renderModel(
      "NullableItemArray",
      z.object({ items: z.array(z.string().nullable()) }),
    ).join("\n");
    expect(rendered).toContain("    items: list[str | None]");
  });

  it("generated ByokProbeResponse retains every probe field", () => {
    const rendered = renderModel("ByokProbeResponse", ByokProbeResponse).join("\n");
    for (const field of ["vision", "reachable", "error_code"]) {
      expect(rendered).toContain(`    ${field}:`);
    }
  });

  it("a nullable string emits a required `str | None`, not an Optional default", () => {
    const rendered = renderModel("ByokProbeResponse", ByokProbeResponse).join("\n");
    expect(rendered).toContain("    error_code: str | None");
    // A nullable-but-required field must not collapse into the optional
    // `Optional[...] | None = None` form — `null` and "absent" are different
    // wires, and the emitted model must keep that distinction.
    expect(rendered).not.toContain("error_code: Optional");
  });

  it("a genuinely optional nullable field still emits the Optional default", () => {
    const rendered = renderModel(
      "NullableOptional",
      z.object({ error_code: z.string().nullable().optional() }),
    ).join("\n");
    expect(rendered).toContain("    error_code: str | None = None");
  });

  it("ByokProbeErrorBody models the agent error envelope shape", () => {
    const shape = ByokProbeErrorBody.safeParse({ error: { code: "egress_blocked" } });
    expect(shape.success).toBe(true);
    const full = ByokProbeErrorBody.safeParse({
      error: { code: "egress_blocked", message: "base_url failed egress validation." },
    });
    expect(full.success).toBe(true);
  });

  it("renders history DTOs with revision, pagination, and a nullable envelope (SESSION-1 #959)", () => {
    const message = renderModel("SessionHistoryMessage", SessionHistoryMessage).join("\n");
    expect(message).toContain("    role: str");
    expect(message).toContain("    content: str");
    expect(message).toContain("    response_data: SessionHistoryMessageResponse_data | None = None");
    expect(message).toContain("    created_at: str");
    expect(message).toContain("    intent: str | None = None");
    expect(message).toContain("    success: bool | None = None");

    const response = renderModel("GetSessionHistoryResponse", GetSessionHistoryResponse).join("\n");
    expect(response).toContain("    messages: list[GetSessionHistoryResponseMessages]");
    expect(response).toContain("    revision: int");
    expect(response).toContain("    next_offset: int | None");
  });

  it("the history payload parses a typed page with a null next offset", () => {
    const page = GetSessionHistoryResponse.safeParse({
      messages: [{ role: "user", content: "hi", response_data: null, created_at: "2026-08-01T00:00:00Z" }],
      revision: 0,
      next_offset: null,
    });
    expect(page.success).toBe(true);
  });

  it("renders the clarify-candidate selection fields on ChatTurnRequest (W1 #1220)", () => {
    const rendered = renderModel("ChatTurnRequest", ChatTurnRequest).join("\n");
    expect(rendered).toContain("    selected_point_ids: list[str] | None = None");
    expect(rendered).toContain("    selected_candidate_ids: list[str] | None = None");
    expect(rendered).toContain("    clarification_id: int | None = None");
  });

  it("a structured candidate pick parses without free text (W1 #1220)", () => {
    const pick = ChatTurnRequest.parse({
      text: "",
      selected_candidate_ids: ["115908", "117696"],
      clarification_id: 4,
    });
    expect(pick.selected_point_ids).toBeUndefined();
  });

  it("the path inventory covers every retained Agent path (exact set)", () => {
    expect(AGENT_PATHS.map((p) => `${p.method} ${p.path}`)).toEqual([
      "GET /",
      "GET /healthz",
      "POST /v1/chat",
      "POST /v1/byok/probe",
      "POST /v1/feedback",
      "GET /v1/conversations",
      "PATCH /v1/conversations/{session_id}",
      "GET /v1/conversations/{session_id}/messages",
      "GET /v1/bangumi/{bangumi_id}/guide",
      "GET /v1/bangumi/nearby",
      "GET /v1/search/preview",
      "POST /v1/photo-search",
      "POST /v1/photo-search/confirm",
      "POST /v1/sessions/adopt",
    ]);
    expect(new Set(AGENT_PATHS.map((p) => p.path)).size).toBe(AGENT_PATHS.length);
  });
});
