/**
 * GENERATED by `pnpm run emit:tool-schemas` — do not edit by hand.
 *
 * The JSON Schema for every catalog tool's parameters, converted once from the
 * zod in `agent-tool-parameters.ts`. See `scripts/emit-tool-schemas.ts` for why
 * this is the repo's only zod↔JSON-Schema conversion (spec §二).
 *
 * This module imports no value, so `workers/edge` can load it under node:test.
 */

import type { CatalogToolName } from "./agent-tool-parameters.js";

/** One parameter's constraints, as the model's provider receives them. */
export interface ToolParameterProperty {
  type: string;
  description?: string;
  minLength?: number;
  pattern?: string;
  enum?: string[];
  exclusiveMinimum?: number;
  maximum?: number;
}

/** One tool's parameter object: what pi validates a tool call against. */
export interface ToolParameterSchema {
  $schema: string;
  type: "object";
  properties: Record<string, ToolParameterProperty>;
  required?: string[];
  additionalProperties: false;
}

/** Every catalog tool's parameter schema, keyed by the name the model calls. */
export const CATALOG_TOOL_SCHEMAS: Record<CatalogToolName, ToolParameterSchema> = {
  resolve_anime: {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
      "title": {
        "type": "string",
        "minLength": 1,
        "description": "The anime title to resolve, as the user wrote it"
      }
    },
    "required": [
      "title"
    ],
    "additionalProperties": false
  },
  search_bangumi: {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
      "bangumi_id": {
        "type": "string",
        "pattern": "^\\d+$",
        "description": "The bangumi id a previous resolve_anime call returned"
      }
    },
    "required": [
      "bangumi_id"
    ],
    "additionalProperties": false
  },
  search_nearby: {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
      "location": {
        "description": "A place name; omit it to search around the user's own coordinates",
        "type": "string",
        "minLength": 1
      },
      "radius_m": {
        "description": "Search radius in metres; omit it to use the place's own radius",
        "type": "integer",
        "exclusiveMinimum": 0,
        "maximum": 9007199254740991
      }
    },
    "additionalProperties": false
  },
  plan_route: {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
      "search_result_ref": {
        "type": "string",
        "minLength": 1,
        "description": "The result_ref a previous search_bangumi or search_nearby outcome returned"
      },
      "pacing": {
        "description": "How densely to pack the day",
        "type": "string",
        "enum": [
          "chill",
          "normal",
          "packed"
        ]
      }
    },
    "required": [
      "search_result_ref"
    ],
    "additionalProperties": false
  },
};
