/**
 * GENERATED by `pnpm run emit:tool-schemas` — do not edit by hand.
 *
 * The JSON Schema for every tool's parameters, converted once from the zod in
 * `agent-tool-parameters.ts`, plus the intent vocabulary read off
 * `chat-data-parts.ts`. See `scripts/emit-tool-schemas.ts` for why this is the
 * repo's only zod↔JSON-Schema conversion (spec §二).
 *
 * This module imports no value, so `workers/edge` can load it under node:test.
 */

import type { CatalogToolName, WebToolName } from "./agent-tool-parameters.js";

/** One parameter's constraints, as the model's provider receives them. */
export interface ToolParameterProperty {
  type: string;
  description?: string;
  minLength?: number;
  pattern?: string;
  enum?: string[];
  exclusiveMinimum?: number;
  maximum?: number;
}

/** One tool's parameter object: what pi validates a tool call against. */
export interface ToolParameterSchema {
  $schema: string;
  type: "object";
  properties: Record<string, ToolParameterProperty>;
  required?: string[];
  additionalProperties: false;
}

/** Every catalog tool's parameter schema, keyed by the name the model calls. */
export const CATALOG_TOOL_SCHEMAS: Record<CatalogToolName, ToolParameterSchema> = {
  resolve_anime: {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
      "title": {
        "type": "string",
        "minLength": 1,
        "pattern": "\\S",
        "description": "The anime title to resolve, as the user wrote it"
      }
    },
    "required": [
      "title"
    ],
    "additionalProperties": false
  },
  search_bangumi: {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
      "bangumi_id": {
        "type": "string",
        "pattern": "^\\d+$",
        "description": "The bangumi id a previous resolve_anime call returned"
      }
    },
    "required": [
      "bangumi_id"
    ],
    "additionalProperties": false
  },
  search_nearby: {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
      "location": {
        "description": "A place name; omit it to search around the user's own coordinates",
        "type": "string",
        "minLength": 1
      },
      "radius_m": {
        "description": "Search radius in metres; omit it to use the place's own radius",
        "type": "integer",
        "exclusiveMinimum": 0,
        "maximum": 9007199254740991
      }
    },
    "additionalProperties": false
  },
  plan_route: {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
      "search_result_ref": {
        "type": "string",
        "minLength": 1,
        "description": "The result_ref a previous search_bangumi or search_nearby outcome returned"
      },
      "pacing": {
        "description": "How densely to pack the day",
        "type": "string",
        "enum": [
          "chill",
          "normal",
          "packed"
        ]
      }
    },
    "required": [
      "search_result_ref"
    ],
    "additionalProperties": false
  },
};

/** Every web tool's parameter schema, keyed by the name the model calls. */
export const WEB_TOOL_SCHEMAS: Record<WebToolName, ToolParameterSchema> = {
  web_search: {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
      "query": {
        "type": "string",
        "pattern": "\\S",
        "description": "The search query. Be specific, and include the language you want results in — for example \"響け！ユーフォニアム Chinese name 中文名\" or \"葬送のフリーレン English title Wikipedia\""
      }
    },
    "required": [
      "query"
    ],
    "additionalProperties": false
  },
  translate_anime_title: {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
      "title": {
        "type": "string",
        "pattern": "\\S",
        "description": "The anime title to translate; it may be in any language, for example \"君の名は。\", \"Your Name\" or \"你的名字\""
      },
      "target_language": {
        "type": "string",
        "enum": [
          "ja",
          "zh",
          "en"
        ],
        "description": "The language code to translate the title into"
      }
    },
    "required": [
      "title",
      "target_language"
    ],
    "additionalProperties": false
  },
};

/** The tool one turn ends on: the model submits its answer by calling it. */
export const ANSWER_TOOL_NAME = "respond";

/** Its parameters: what the model may author about its own answer (#1283). */
export const ANSWER_TOOL_SCHEMA: ToolParameterSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "kind": {
      "type": "string",
      "enum": [
        "search",
        "route",
        "clarify",
        "greeting",
        "qa"
      ],
      "description": "What this answer is: search (results were found), route (an itinerary was planned), clarify (the user must choose), greeting, or qa"
    },
    "message": {
      "type": "string",
      "pattern": "\\S",
      "description": "The reply shown to the user. Brief for search, route and clarify because the app renders the rich UI; a full answer for qa"
    },
    "reason": {
      "description": "For kind=clarify only: the pending tool outcome's own reason, copied exactly",
      "type": "string",
      "pattern": "\\S"
    }
  },
  "required": [
    "kind",
    "message"
  ],
  "additionalProperties": false
};

/** Every intent `ChatResponseDataPart` accepts, in its declaration order. */
export const CHAT_RESPONSE_INTENTS = [
  "search_bangumi",
  "search_nearby",
  "plan_route",
  "plan_selected",
  "plan_multi",
  "general_qa",
  "greet_user",
  "clarify",
  "partial",
  "blocked",
  "error",
  "unknown",
] as const;

/** One intent of the `data-response` part. */
export type ChatResponseIntent = (typeof CHAT_RESPONSE_INTENTS)[number];
