"""SQLModel mapping of ``public.turn_reservations`` (TURN-2 #949, TURN-3 #951).

``id`` is an Animichi-owned identity generated by the database's native
``uuidv7()`` default; the (session_id, turn_key) pair and the revision CAS
remain the semantic keys (#992).
"""

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from sqlalchemy import Column, DateTime, Integer, Table, Text, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlmodel import Field, SQLModel


class TurnReservationModel(SQLModel, table=True):
    """Row of ``turn_reservations`` — one durable turn lifecycle record."""

    __tablename__ = "turn_reservations"

    __table__: Table

    id: UUID | None = Field(
        default=None,
        sa_column=Column(
            PgUUID(as_uuid=True),
            primary_key=True,
            server_default=text("uuidv7()"),
        ),
    )
    session_id: str | None = Field(default=None, sa_column=Column(Text))
    turn_key: str = Field(sa_column=Column(Text, nullable=False))
    payer: str = Field(sa_column=Column(Text, nullable=False))
    identity_id: str | None = Field(default=None, sa_column=Column(Text))
    revision: int = Field(sa_column=Column(Integer, nullable=False))
    digest: str | None = Field(default=None, sa_column=Column(Text))
    status: str = Field(sa_column=Column(Text, nullable=False))
    created_at: datetime = Field(
        sa_column=Column(DateTime(timezone=True), nullable=False)
    )
    updated_at: datetime = Field(
        sa_column=Column(DateTime(timezone=True), nullable=False)
    )
    lease_owner: str = Field(sa_column=Column(Text, nullable=False))
    lease_expires_at: datetime = Field(
        sa_column=Column(DateTime(timezone=True), nullable=False)
    )
    #: Canonical sha256 hex of the turn request (AC4 conflict detection).
    request_digest: str | None = Field(default=None, sa_column=Column(Text))
    #: Serialized committed wire output, recoverable on replay (AC3).
    outcome_payload: object | None = Field(default=None, sa_column=Column(JSONB))


reservation_table: Table = TurnReservationModel.__table__
