/**
 * Contract-derived seed fixtures for the catalog integration suite.
 *
 * Every identity-bearing value a shared contract schema owns — the work id, the
 * latitude/longitude pair, a candidate and an outcome — is parsed through
 * `packages/contract` (the cross-service source of truth) at construction, so a
 * fixture that no longer matches the wire contract fails loudly HERE instead of
 * surfacing as a downstream 400/500 in a live integration run. The INSERT
 * statements are emitted from the same records the assertions read, so the seed
 * and the expectation cannot drift apart.
 *
 * The table and column NAMES used to be read off the Drizzle schema, which left
 * the repository with #1633. They are written out below instead: the committed
 * Prisma chain is the schema authority now, and it has no string-keyed shape to
 * look a column up in. Nothing is lost by the change — a name that stops
 * matching the chain fails on the seeding statement itself, which is where a
 * wrong name was always going to surface.
 *
 * Every integration suite seeds through these builders; a raw `INSERT INTO` for
 * a builder-covered table in a suite is refused by
 * `./catalog-seed.worker.test.ts`. A seed the builders cannot express — a set
 * generated by the database's own `generate_series` — lives in its own fixture
 * module, so the table names still have exactly one owner per shape.
 */

import type pg from "pg";
import {
  AnimeCandidate,
  Latitude,
  Longitude,
  Point,
  PointsByBangumiIdInput,
  PopularBangumi,
  ResolveOutcome,
} from "@animichi/contract";

/** A parameterized statement: placeholder SQL plus its positional values. */
export interface SeedStatement {
  text: string;
  values: (string | number | boolean | null)[];
}

/** Run one builder statement on `pool`. */
export async function runSeed(pool: pg.Pool, statement: SeedStatement): Promise<void> {
  await pool.query(statement.text, statement.values);
}

/** The optional `bangumi` columns the shared builders can carry. */
export interface WorkSeedFields {
  titleCn?: string;
  epsCount?: number;
  rating?: number;
  pointsCount?: number;
}

export interface WorkSeed extends WorkSeedFields {
  workId: string;
  title: string;
}

/** The optional `points` columns the shared builders can carry. */
export interface PointSeedFields {
  episode?: number;
  timeSeconds?: number;
  image?: string;
  city?: string;
}

export interface PointSeed extends PointSeedFields {
  id: string;
  workId: string;
  name: string;
  latitude: number;
  longitude: number;
}

export interface AliasSeed {
  workId: string;
  alias: string;
  normalized: string;
  source: string;
  priority: number;
}

export interface ClusterVersionSeed {
  workId: string;
  version: number;
  isCurrent: boolean;
}

/** A bangumi id the contract accepts on `pointsByBangumiId` (bare Bangumi subject id). */
export function contractBangumiId(candidate: string): string {
  return PointsByBangumiIdInput.parse({ bangumi_id: candidate }).bangumi_id;
}

/**
 * One work seed.
 *
 * The id goes through `pointsByBangumiId`'s own regex, and the columns a shared
 * model owns (`title_cn`, `rating`, `points_count`) through `PopularBangumi`,
 * so a `lucky-star`-style id or a negative point count fails at construction.
 * `eps_count` has no contract model; it is typed here and lands on the chain.
 */
export function workSeed(id: string, title: string, fields: WorkSeedFields = {}): WorkSeed {
  const workId = contractBangumiId(id);
  PopularBangumi.parse({
    bangumi_id: workId,
    title,
    title_cn: fields.titleCn ?? null,
    cover_url: null,
    city: null,
    points_count: fields.pointsCount ?? 0,
    rating: fields.rating ?? null,
  });
  return { workId, title, ...fields };
}

const POINT_FIELDS = Point.omit({ screenshot_url: true });

/**
 * One point seed.
 *
 * The coordinates go through `Latitude` / `Longitude`, and the scene columns
 * through the shared `Point` model; `image` is the chain's nullable counterpart
 * of that model's required `screenshot_url`, so it is omitted from the parse.
 */
export function pointSeed(
  id: string,
  work: WorkSeed,
  name: string,
  latitude: number,
  longitude: number,
  fields: PointSeedFields = {},
): PointSeed {
  POINT_FIELDS.parse({
    id,
    name,
    bangumi_id: work.workId,
    episode: fields.episode,
    time_seconds: fields.timeSeconds,
    city: fields.city,
    latitude,
    longitude,
  });
  return {
    id,
    workId: work.workId,
    name,
    latitude: Latitude.parse(latitude),
    longitude: Longitude.parse(longitude),
    ...fields,
  };
}

export function aliasSeed(
  work: WorkSeed,
  alias: string,
  normalized: string,
  source: string,
  priority: number,
): AliasSeed {
  return { workId: work.workId, alias, normalized, source, priority };
}

export function clusterVersionSeed(work: WorkSeed, version: number, isCurrent: boolean): ClusterVersionSeed {
  return { workId: work.workId, version, isCurrent };
}

/** Expected resolve candidate, validated against the shared `AnimeCandidate`. */
export function candidateOf(work: WorkSeed, pointsCount: number): AnimeCandidate {
  return AnimeCandidate.parse({
    bangumi_id: work.workId,
    title: work.title,
    points_count: pointsCount,
  });
}

/** Expected `resolved` outcome, validated against the shared `ResolveOutcome`. */
export function resolvedOutcome(work: WorkSeed, pointsCount: number): ResolveOutcome {
  return ResolveOutcome.parse({ outcome: "resolved", match: candidateOf(work, pointsCount) });
}

/** Expected `needs_disambiguation` outcome, validated against `ResolveOutcome`. */
export function ambiguousOutcome(candidates: readonly AnimeCandidate[]): ResolveOutcome {
  return ResolveOutcome.parse({
    outcome: "needs_disambiguation",
    reason: "anime_ambiguity",
    candidates,
  });
}

function placeholderGroup(row: number, columns: number): string {
  const slots = Array.from({ length: columns }, (_, index) =>
    `$${String(row * columns + index + 1)}`);
  return `(${slots.join(", ")})`;
}

function statement(
  table: string,
  columns: readonly string[],
  rows: readonly (readonly (string | number | boolean | null)[])[],
): SeedStatement {
  const groups = rows.map((_, row) => placeholderGroup(row, columns.length));
  return { text: `INSERT INTO ${table} (${columns.join(", ")}) VALUES ${groups.join(", ")}`, values: rows.flatMap((row) => [...row]) };
}

export function workInsert(seeds: readonly WorkSeed[]): SeedStatement {
  return statement(
    "bangumi",
    ["id", "title", "title_cn", "eps_count", "rating", "points_count"],
    seeds.map((s) => [
      s.workId, s.title, s.titleCn ?? null, s.epsCount ?? null, s.rating ?? null, s.pointsCount ?? 0,
    ]),
  );
}

/**
 * Points, written through their source geometry.
 *
 * `latitude` / `longitude` are NOT written directly: the Prisma data plane makes
 * them generated columns over `location` (#1626, spec §4.8.1), so a scalar write
 * is `cannot insert a non-DEFAULT value into column "latitude"` (`428C9`), and
 * `location` is the column spatial search reads anyway.
 */
export function pointInsert(seeds: readonly PointSeed[]): SeedStatement {
  const values = seeds.map((s): (string | number | null)[] => [
    s.id, s.workId, s.name, s.episode ?? null, s.timeSeconds ?? 0, s.image ?? null, s.city ?? null,
    s.longitude, s.latitude,
  ]);
  return {
    text: "INSERT INTO points (id, bangumi_id, name, episode, time_seconds, image, city, location)"
      + ` VALUES ${seeds.map((_, index) => pointGroup(index)).join(", ")}`,
    values: values.flatMap((row) => [...row]),
  };
}

/** Placeholders one point row binds: id, work, name, scene, image, city, longitude, latitude. */
const POINT_SLOTS = 9;

/** One point row's placeholder group: seven scalars, then the geometry over the
 * longitude/latitude pair that follows them. */
function pointGroup(index: number): string {
  const slot = (offset: number): string => `$${String(index * POINT_SLOTS + offset)}`;
  const scalars = [1, 2, 3, 4, 5, 6, 7].map((offset) => slot(offset)).join(", ");
  return `(${scalars}, ST_SetSRID(ST_MakePoint(${slot(8)}, ${slot(9)}), 4326)::geography)`;
}

export function aliasInsert(seeds: readonly AliasSeed[]): SeedStatement {
  return statement(
    "aliases",
    ["bangumi_id", "alias", "alias_normalized", "source", "priority"],
    seeds.map((s) => [s.workId, s.alias, s.normalized, s.source, s.priority]),
  );
}

export function clusterVersionInsert(seeds: readonly ClusterVersionSeed[]): SeedStatement {
  return statement(
    "cluster_version",
    ["bangumi_id", "version", "is_current"],
    seeds.map((s) => [s.workId, s.version, s.isCurrent]),
  );
}
