name: CD staging
on:
  push:
    branches: [main]
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      catalog: ${{ steps.f.outputs.catalog }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: f
        with:
          filters: |
            catalog: ['workers/catalog/**', 'packages/contract/**', 'db/migrations/**', 'infra/**']
  catalog:
    needs: changes
    if: ${{ needs.changes.outputs.catalog == 'true' }}
    uses: ./.github/workflows/_deploy-component.yml
    with:
      component: catalog
      environment: staging
      pulumi_stack: staging
    secrets: inherit
